name: autoscore_frontent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1  # phiên bản mới nhất của google_sign_in
  http: ^1.2.2  # để gọi API từ Flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
